const { createClient } = require('@supabase/supabase-js');
const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.join(__dirname, '..', '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

async function run() {
    const userId = 'bc63c065-9bcc-4793-bedc-f0960406425b';
    const { data: profile, error } = await supabaseAdmin
        .from('profiles')
        .select('facebook_token, ad_account_id, selected_page_token')
        .eq('id', userId)
        .single();
        
    if (error || !profile || !profile.facebook_token || !profile.ad_account_id) {
        console.error("Profile or facebook credentials not found:", error);
        return;
    }

    const token = profile.facebook_token;
    const adAccountId = profile.ad_account_id;
    const pageToken = profile.selected_page_token;

    console.log(`Fetching campaigns for Ad Account: ${adAccountId}...`);
    const campaignsUrl = `https://graph.facebook.com/v19.0/${adAccountId}/campaigns?fields=id,name,status,effective_status,objective,created_time&access_token=${token}`;
    const campaignsRes = await fetch(campaignsUrl);
    const campaignsData = await campaignsRes.json();

    if (campaignsData.error) {
        console.error("Error fetching campaigns:", campaignsData.error);
        return;
    }

    const campaigns = campaignsData.data || [];
    console.log(`Found ${campaigns.length} campaigns:`);
    
    // Sort campaigns by created_time descending
    campaigns.sort((a, b) => new Date(b.created_time) - new Date(a.created_time));

    for (const c of campaigns) {
        console.log(`\n================================================================`);
        console.log(`Campaign: "${c.name}" (ID: ${c.id})`);
        console.log(`Status: ${c.status} | Effective Status: ${c.effective_status} | Objective: ${c.objective}`);
        console.log(`Created: ${c.created_time}`);

        // Fetch insights to get lead count
        const insightsUrl = `https://graph.facebook.com/v19.0/${c.id}/insights?fields=actions,inline_link_clicks,impressions,spend&date_preset=lifetime&access_token=${token}`;
        const insightsRes = await fetch(insightsUrl);
        const insightsData = await insightsRes.json();
        
        let metaLeadCount = 0;
        if (insightsData.data && insightsData.data.length > 0) {
            const insights = insightsData.data[0];
            const actions = insights.actions || [];
            const leadAction = actions.find(a => a.action_type === 'lead' || a.action_type === 'onsite_conversion.lead_grouped');
            if (leadAction) {
                metaLeadCount = parseInt(leadAction.value);
            }
            console.log(`Insights: Spend=${insights.spend} | Impressions=${insights.impressions} | Leads=${metaLeadCount}`);
        } else {
            console.log(`No insights/spending data found (or inactive).`);
        }

        // Fetch Ads under this campaign to see what forms/leads are generated
        const adsUrl = `https://graph.facebook.com/v19.0/${c.id}/ads?fields=id,name,status,creative{id,object_story_spec}&access_token=${token}`;
        const adsRes = await fetch(adsUrl);
        const adsData = await adsRes.json();

        const ads = adsData.data || [];
        console.log(`Found ${ads.length} ads in this campaign.`);

        for (const ad of ads) {
            console.log(`  - Ad: "${ad.name}" (ID: ${ad.id})`);
            
            // Query leads for this ad directly
            const adLeadsUrl = `https://graph.facebook.com/v19.0/${ad.id}/leads?fields=id,created_time,field_data,form_id&access_token=${pageToken || token}`;
            const adLeadsRes = await fetch(adLeadsUrl);
            const adLeadsData = await adLeadsRes.json();

            if (adLeadsData.error) {
                console.error(`    Error fetching leads for Ad ${ad.id}:`, adLeadsData.error.message);
                continue;
            }

            const adLeads = adLeadsData.data || [];
            console.log(`    Leads generated by this Ad: ${adLeads.length}`);
            
            for (const lead of adLeads) {
                let name = 'Unknown', phone = '', email = '';
                lead.field_data?.forEach(field => {
                    const fieldName = field.name.toLowerCase();
                    const fieldValue = field.values ? field.values[0] : '';
                    if (fieldName === 'full_name' || fieldName === 'name') name = fieldValue;
                    else if (fieldName === 'email') email = fieldValue;
                    else if (fieldName === 'phone_number' || fieldName === 'phone' || fieldName === 'mobile_number') phone = fieldValue;
                });
                
                // Check if exists in DB
                const { data: dbLead } = await supabaseAdmin
                    .from('leads')
                    .select('id')
                    .eq('facebook_lead_id', lead.id)
                    .maybeSingle();

                console.log(`      * Lead ID: ${lead.id} | Name: ${name} | Email: ${email} | Phone: ${phone} | CRM: ${dbLead ? '✅ Found' : '❌ MISSING'}`);
            }
        }
    }
}

run().catch(console.error);
